#############################################################################
# Makefile for building: testing2
# Generated by qmake (3.1) (Qt 6.1.0)
# Project:  ..\testirovanie2\testing2.pro
# Template: subdirs
# Command: D:\Qt\6.1.0\mingw81_64\bin\qmake.exe -o Makefile ..\testirovanie2\testing2.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = D:\Qt\6.1.0\mingw81_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = D:\Qt\6.1.0\mingw81_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = D:\Qt\6.1.0\mingw81_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		sub-app \
		sub-tests


sub-app-qmake_all:  FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && $(QMAKE) -o Makefile C:\Users\dmitr\Downloads\testirovanie2\app\app.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd app\ && $(MAKE) -f Makefile qmake_all
sub-app: FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\dmitr\Downloads\testirovanie2\app\app.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-app-make_first-ordered: FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\dmitr\Downloads\testirovanie2\app\app.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-app-make_first: FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\dmitr\Downloads\testirovanie2\app\app.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-app-all-ordered: FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\dmitr\Downloads\testirovanie2\app\app.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-app-all: FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\dmitr\Downloads\testirovanie2\app\app.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-app-clean-ordered: FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\dmitr\Downloads\testirovanie2\app\app.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-app-clean: FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\dmitr\Downloads\testirovanie2\app\app.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-app-distclean-ordered: FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\dmitr\Downloads\testirovanie2\app\app.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-app-distclean: FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\dmitr\Downloads\testirovanie2\app\app.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-app-install_subtargets-ordered: FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\dmitr\Downloads\testirovanie2\app\app.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-app-install_subtargets: FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\dmitr\Downloads\testirovanie2\app\app.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-app-uninstall_subtargets-ordered: FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\dmitr\Downloads\testirovanie2\app\app.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-app-uninstall_subtargets: FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\dmitr\Downloads\testirovanie2\app\app.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-tests-qmake_all: sub-app-qmake_all FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && $(QMAKE) -o Makefile C:\Users\dmitr\Downloads\testirovanie2\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd tests\ && $(MAKE) -f Makefile qmake_all
sub-tests: FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\dmitr\Downloads\testirovanie2\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-tests-make_first-ordered: sub-app-make_first-ordered  FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\dmitr\Downloads\testirovanie2\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-tests-make_first: FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\dmitr\Downloads\testirovanie2\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-tests-all-ordered: sub-app-all-ordered  FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\dmitr\Downloads\testirovanie2\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-tests-all: FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\dmitr\Downloads\testirovanie2\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-tests-clean-ordered: sub-app-clean-ordered  FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\dmitr\Downloads\testirovanie2\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-tests-clean: FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\dmitr\Downloads\testirovanie2\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-tests-distclean-ordered: sub-app-distclean-ordered  FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\dmitr\Downloads\testirovanie2\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-tests-distclean: FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\dmitr\Downloads\testirovanie2\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-tests-install_subtargets-ordered: sub-app-install_subtargets-ordered  FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\dmitr\Downloads\testirovanie2\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-tests-install_subtargets: FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\dmitr\Downloads\testirovanie2\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-tests-uninstall_subtargets-ordered: sub-app-uninstall_subtargets-ordered  FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\dmitr\Downloads\testirovanie2\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-tests-uninstall_subtargets: FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\dmitr\Downloads\testirovanie2\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall

Makefile: ../testirovanie2/testing2.pro D:/Qt/6.1.0/mingw81_64/mkspecs/win32-g++/qmake.conf D:/Qt/6.1.0/mingw81_64/mkspecs/features/spec_pre.prf \
		D:/Qt/6.1.0/mingw81_64/mkspecs/features/device_config.prf \
		D:/Qt/6.1.0/mingw81_64/mkspecs/common/sanitize.conf \
		D:/Qt/6.1.0/mingw81_64/mkspecs/common/gcc-base.conf \
		D:/Qt/6.1.0/mingw81_64/mkspecs/common/g++-base.conf \
		D:/Qt/6.1.0/mingw81_64/mkspecs/features/win32/windows_vulkan_sdk.prf \
		D:/Qt/6.1.0/mingw81_64/mkspecs/common/windows-vulkan.conf \
		D:/Qt/6.1.0/mingw81_64/mkspecs/common/g++-win32.conf \
		D:/Qt/6.1.0/mingw81_64/mkspecs/common/windows-desktop.conf \
		D:/Qt/6.1.0/mingw81_64/mkspecs/qconfig.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_ext_freetype.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_ext_libpng.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_concurrent.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_core.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_core_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_dbus.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_dbus_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_designer.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_designer_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_entrypoint_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_gui.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_gui_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_help.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_help_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_labsanimation.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_labsanimation_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_labssettings.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_labssettings_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_labssharedimage.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_linguist.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_linguist_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_network.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_network_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_opengl.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_opengl_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_printsupport.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_qml.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_qml_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_qmldom_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_qmltest.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_quick.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_quick_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_quicklayouts.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_sql.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_sql_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_svg.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_svg_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_testlib.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_testlib_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_tools_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_uiplugin.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_uitools.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_uitools_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_widgets.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_widgets_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_xml.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_xml_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_zlib_private.pri \
		D:/Qt/6.1.0/mingw81_64/mkspecs/features/qt_functions.prf \
		D:/Qt/6.1.0/mingw81_64/mkspecs/features/qt_config.prf \
		D:/Qt/6.1.0/mingw81_64/mkspecs/win32-g++/qmake.conf \
		D:/Qt/6.1.0/mingw81_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		D:/Qt/6.1.0/mingw81_64/mkspecs/features/exclusive_builds.prf \
		D:/Qt/6.1.0/mingw81_64/mkspecs/features/toolchain.prf \
		D:/Qt/6.1.0/mingw81_64/mkspecs/features/default_pre.prf \
		D:/Qt/6.1.0/mingw81_64/mkspecs/features/win32/default_pre.prf \
		D:/Qt/6.1.0/mingw81_64/mkspecs/features/resolve_config.prf \
		D:/Qt/6.1.0/mingw81_64/mkspecs/features/exclusive_builds_post.prf \
		D:/Qt/6.1.0/mingw81_64/mkspecs/features/default_post.prf \
		D:/Qt/6.1.0/mingw81_64/mkspecs/features/qml_debug.prf \
		D:/Qt/6.1.0/mingw81_64/mkspecs/features/entrypoint.prf \
		D:/Qt/6.1.0/mingw81_64/mkspecs/features/precompile_header.prf \
		D:/Qt/6.1.0/mingw81_64/mkspecs/features/warn_on.prf \
		D:/Qt/6.1.0/mingw81_64/mkspecs/features/qmake_use.prf \
		D:/Qt/6.1.0/mingw81_64/mkspecs/features/file_copies.prf \
		D:/Qt/6.1.0/mingw81_64/mkspecs/features/win32/windows.prf \
		D:/Qt/6.1.0/mingw81_64/mkspecs/features/testcase_targets.prf \
		D:/Qt/6.1.0/mingw81_64/mkspecs/features/exceptions.prf \
		D:/Qt/6.1.0/mingw81_64/mkspecs/features/yacc.prf \
		D:/Qt/6.1.0/mingw81_64/mkspecs/features/lex.prf \
		../testirovanie2/testing2.pro
	$(QMAKE) -o Makefile ..\testirovanie2\testing2.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
D:/Qt/6.1.0/mingw81_64/mkspecs/features/spec_pre.prf:
D:/Qt/6.1.0/mingw81_64/mkspecs/features/device_config.prf:
D:/Qt/6.1.0/mingw81_64/mkspecs/common/sanitize.conf:
D:/Qt/6.1.0/mingw81_64/mkspecs/common/gcc-base.conf:
D:/Qt/6.1.0/mingw81_64/mkspecs/common/g++-base.conf:
D:/Qt/6.1.0/mingw81_64/mkspecs/features/win32/windows_vulkan_sdk.prf:
D:/Qt/6.1.0/mingw81_64/mkspecs/common/windows-vulkan.conf:
D:/Qt/6.1.0/mingw81_64/mkspecs/common/g++-win32.conf:
D:/Qt/6.1.0/mingw81_64/mkspecs/common/windows-desktop.conf:
D:/Qt/6.1.0/mingw81_64/mkspecs/qconfig.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_ext_freetype.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_ext_libpng.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_concurrent.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_concurrent_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_core.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_core_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_dbus.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_dbus_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_designer.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_designer_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_entrypoint_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_fb_support_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_gui.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_gui_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_help.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_help_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_labsanimation.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_labsanimation_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_labsqmlmodels.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_labssettings.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_labssettings_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_labssharedimage.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_labssharedimage_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_linguist.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_linguist_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_network.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_network_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_opengl.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_opengl_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_openglwidgets.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_openglwidgets_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_printsupport.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_printsupport_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_qml.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_qml_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_qmldom_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_qmllocalstorage.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_qmlmodels.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_qmltest.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_qmltest_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_quick.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_quick_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_quicklayouts.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_quicklayouts_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_quickwidgets.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_sql.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_sql_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_svg.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_svg_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_svgwidgets.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_svgwidgets_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_testlib.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_testlib_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_tools_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_uiplugin.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_uitools.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_uitools_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_widgets.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_widgets_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_xml.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_xml_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/modules/qt_lib_zlib_private.pri:
D:/Qt/6.1.0/mingw81_64/mkspecs/features/qt_functions.prf:
D:/Qt/6.1.0/mingw81_64/mkspecs/features/qt_config.prf:
D:/Qt/6.1.0/mingw81_64/mkspecs/win32-g++/qmake.conf:
D:/Qt/6.1.0/mingw81_64/mkspecs/features/spec_post.prf:
.qmake.stash:
D:/Qt/6.1.0/mingw81_64/mkspecs/features/exclusive_builds.prf:
D:/Qt/6.1.0/mingw81_64/mkspecs/features/toolchain.prf:
D:/Qt/6.1.0/mingw81_64/mkspecs/features/default_pre.prf:
D:/Qt/6.1.0/mingw81_64/mkspecs/features/win32/default_pre.prf:
D:/Qt/6.1.0/mingw81_64/mkspecs/features/resolve_config.prf:
D:/Qt/6.1.0/mingw81_64/mkspecs/features/exclusive_builds_post.prf:
D:/Qt/6.1.0/mingw81_64/mkspecs/features/default_post.prf:
D:/Qt/6.1.0/mingw81_64/mkspecs/features/qml_debug.prf:
D:/Qt/6.1.0/mingw81_64/mkspecs/features/entrypoint.prf:
D:/Qt/6.1.0/mingw81_64/mkspecs/features/precompile_header.prf:
D:/Qt/6.1.0/mingw81_64/mkspecs/features/warn_on.prf:
D:/Qt/6.1.0/mingw81_64/mkspecs/features/qmake_use.prf:
D:/Qt/6.1.0/mingw81_64/mkspecs/features/file_copies.prf:
D:/Qt/6.1.0/mingw81_64/mkspecs/features/win32/windows.prf:
D:/Qt/6.1.0/mingw81_64/mkspecs/features/testcase_targets.prf:
D:/Qt/6.1.0/mingw81_64/mkspecs/features/exceptions.prf:
D:/Qt/6.1.0/mingw81_64/mkspecs/features/yacc.prf:
D:/Qt/6.1.0/mingw81_64/mkspecs/features/lex.prf:
../testirovanie2/testing2.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile ..\testirovanie2\testing2.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"

qmake_all: sub-app-qmake_all sub-tests-qmake_all FORCE

make_first: sub-app-make_first-ordered sub-tests-make_first-ordered  FORCE
all: sub-app-all-ordered sub-tests-all-ordered  FORCE
clean: sub-app-clean-ordered sub-tests-clean-ordered  FORCE
distclean: sub-app-distclean-ordered sub-tests-distclean-ordered  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-app-install_subtargets-ordered sub-tests-install_subtargets-ordered FORCE
uninstall_subtargets: sub-app-uninstall_subtargets-ordered sub-tests-uninstall_subtargets-ordered FORCE

sub-app-debug_ordered:
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\dmitr\Downloads\testirovanie2\app\app.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-tests-debug_ordered: sub-app-debug_ordered 
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\dmitr\Downloads\testirovanie2\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
debug: sub-app-debug_ordered sub-tests-debug_ordered

sub-app-release_ordered:
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\dmitr\Downloads\testirovanie2\app\app.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-tests-release_ordered: sub-app-release_ordered 
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\dmitr\Downloads\testirovanie2\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
release: sub-app-release_ordered sub-tests-release_ordered

sub-app-check_ordered:
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\dmitr\Downloads\testirovanie2\app\app.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-tests-check_ordered: sub-app-check_ordered 
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\dmitr\Downloads\testirovanie2\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
check: sub-app-check_ordered sub-tests-check_ordered

sub-app-benchmark_ordered:
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\dmitr\Downloads\testirovanie2\app\app.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-tests-benchmark_ordered: sub-app-benchmark_ordered 
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\dmitr\Downloads\testirovanie2\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-app-benchmark_ordered sub-tests-benchmark_ordered
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

